import type { Customer } from './types';

export const mockCustomers: Customer[] = [
  {
    id: 'C001',
    name: 'John Smith',
    address: '1234 Palm Beach Blvd, Fort Myers, FL 33901',
    lat: 26.6406,
    lng: -81.8723,
    notes: 'Customer has a dog named Buddy. Make sure to close the gate. Large palm trees in front yard need trimming.',
    serviceRequested: 'Weekly Mowing & Edging',
    servicePreferences: {
      preferredDays: ['monday', 'wednesday', 'friday'],
      preferredTimeRange: { start: '08:00', end: '12:00' },
      serviceFrequency: 'weekly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C002',
    name: 'Maria Garcia',
    address: '5678 Gulf Shore Dr, Naples, FL 34102',
    lat: 26.1420,
    lng: -81.7948,
    notes: 'Sprinkler system runs on Wednesdays at 6 AM. Back lawn is sloped. Pool area needs special attention.',
    serviceRequested: 'Fertilization & Weed Control',
    servicePreferences: {
      preferredDays: ['tuesday', 'thursday'],
      preferredTimeRange: { start: '13:00', end: '17:00' },
      serviceFrequency: 'biweekly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C003',
    name: 'David Johnson',
    address: '9012 Tamiami Trail, Sarasota, FL 34236',
    lat: 27.3364,
    lng: -82.5307,
    notes: 'Wants a quote for landscaping the flower beds next visit. Large oak tree in backyard.',
    serviceRequested: 'Spring Cleanup & Mulching',
    servicePreferences: {
      preferredDays: ['monday', 'friday'],
      preferredTimeRange: { start: '09:00', end: '15:00' },
      serviceFrequency: 'weekly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C004',
    name: 'Sarah Wilson',
    address: '3456 Bayshore Blvd, Tampa, FL 33609',
    lat: 27.9506,
    lng: -82.4572,
    notes: 'Access key for the back gate is under the green pot. Waterfront property with special drainage needs.',
    serviceRequested: 'Weekly Mowing & Edging',
    servicePreferences: {
      preferredDays: ['wednesday', 'saturday'],
      preferredTimeRange: { start: '10:00', end: '16:00' },
      serviceFrequency: 'monthly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C005',
    name: 'Michael Rodriguez',
    address: '7890 Orange Blossom Trail, Orlando, FL 32839',
    lat: 28.5383,
    lng: -81.3792,
    notes: 'Commercial property with large parking lot. Needs weekly maintenance.',
    serviceRequested: 'Commercial Landscaping',
    servicePreferences: {
      preferredDays: ['monday', 'wednesday'],
      preferredTimeRange: { start: '07:00', end: '11:00' },
      serviceFrequency: 'weekly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'C006',
    name: 'Jennifer Lee',
    address: '2345 Collins Ave, Miami Beach, FL 33139',
    lat: 25.7617,
    lng: -80.1918,
    notes: 'High-end residential property. Requires premium service. Pool deck area included.',
    serviceRequested: 'Premium Lawn Care & Pool Deck Maintenance',
    servicePreferences: {
      preferredDays: ['tuesday', 'friday'],
      preferredTimeRange: { start: '08:00', end: '14:00' },
      serviceFrequency: 'weekly',
    },
    serviceHistory: [],
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
